-- Oracle Date Conversion Functions
SELECT TO_CHAR(SYSDATE, 'DD-MM-YYYY') FROM dual;
SELECT TO_CHAR(SYSDATE, 'DD-MON-YYYY HH24:MI:SS') FROM dual;
SELECT TO_DATE('22-09-2026', 'DD-MM-YYYY') FROM dual;
